# Generated by Django 3.2.9 on 2021-12-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('line1', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.EmailField(max_length=200)),
                ('zip', models.IntegerField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
