# Generated by Django 3.2.9 on 2021-12-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
