# Generated by Django 3.2.9 on 2021-12-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20211203_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
